[package]
name = "bitcoincore_zmq_integration_tests"
version = "1.0.0"
edition = "2021"

[dependencies]
bitcoin = "0.31.1"
bitcoincore-rpc = "0.18.0"
bitcoincore-zmq = { path = "..", features = ["async"] }
futures = "0.3.28"
tokio = { version = "1.35.0", features = ["full"] }
