[package]
name = "bitcoincore_zmq_integration_tests"
version = "1.0.0"
edition = "2021"

[dependencies]
bitcoin = "0.32.2"
bitcoincore-rpc = "0.19.0"
bitcoincore-zmq = { path = "..", features = ["async"] }
futures = "0.3.30"
tokio = { version = "1.38.0", features = ["full"] }
