[package]
name = "bitcoincore_zmq_integration_tests"
version = "1.0.0"
edition = "2021"

[dependencies]
bitcoin = "0.30.0"
bitcoincore-rpc = "0.17.0"
bitcoincore-zmq = { path = "..", features = ["async"] }
futures = "0.3.28"
tokio = { version = "1.35.0", features = ["time", "rt-multi-thread"] }
