name: Build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        args:
          [
            "--no-default-features",
            "--features async",
          ]
    steps:
    - uses: actions/checkout@v3
    - name: Check
      run: |
        cargo fmt --check
        cargo clippy ${{ matrix.args }} -- -D warnings
    - name: Build
      run: cargo build ${{ matrix.args }} --verbose
    - name: Run tests
      run: cargo test ${{ matrix.args }} --verbose
